[book]
authors = ["AbelitoGamer"]
language = "es"
multilingual = false
src = "src"
title = "Funky Maker: Guide"


[output.html]
git-repository-url = "https://github.com/AbelitoGamer/Funky-Guide/tree/main/"
edit-url-template = "https://github.com/AbelitoGamer/Funky-Guide/edit/main/{path}"