[book]
authors = ["AbelitoGamer"]
language = "es"
multilingual = false
src = "src"
title = "Funky Maker: Guide"


[output.html]
git-repository-url = "https://github.com/FunkinCrew/funkin-modding-docs/tree/main/"
edit-url-template = "https://github.com/FunkinCrew/funkin-modding-docs/edit/main/{path}"
